# Generated by Django 4.2 on 2025-07-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=300)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'blogs',
            },
        ),
    ]
